### PR TITLE
Moved to Swift 3

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pronebird** [comment]
Thanks so much!

**Comment by ThePowerOfSwift** [comment]
Merge current "master" to "Swift-3.0" branch, and make it compilable with Xcode 8.0.

Swift 3 Support.

**Comment by pronebird** [comment]
@mihailsalari yeah it runs pretty well on Xcode 8 beta 6

**Comment by ThePowerOfSwift** [comment]
@pronebird :) You Welcome :)

**Pull request merged**
